from .views import (
    TacheListCreateView,
    TacheDetailView,
    ConsultantListAPIView,
    ConsultantDetailAPIView,
    UtilisateurDetailView,
    ForgotPasswordView,
    ValidateResetTokenView,
    ResetPasswordView,
    ChefProjetConsultantsView,
    RegisterView,
    CurrentUserView,
)from .views import (
    TacheListCreateView,
    TacheDetailView,
    ConsultantListAPIView,
    ConsultantDetailAPIView,
    UtilisateurDetailView,
    ForgotPasswordView,
    ValidateResetTokenView,
    ResetPasswordView,
    ChefProjetConsultantsView,
    RegisterView,
    CurrentUserView,
)