# Generated by Django 6.0.5 on 2026-05-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('motDePasse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('photoProfil', models.ImageField(blank=True, null=True, upload_to='photos_profils/')),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('dernierConnexion', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('dateDerniereMessage', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('objectsif', models.CharField(max_length=100)),
                ('dateDebut', models.DateField()),
                ('dateFinPrevue', models.DateField()),
                ('dateFinReelle', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(max_length=50)),
                ('avancementGlobale', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='chefProjet',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ramaqs_management_plateforme.utilisateur')),
                ('specialite', models.CharField(max_length=100)),
                ('certifications', models.CharField(max_length=200)),
            ],
            bases=('ramaqs_management_plateforme.utilisateur',),
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ramaqs_management_plateforme.utilisateur')),
                ('societe', models.CharField(max_length=100)),
                ('secteurActivite', models.CharField(max_length=100)),
                ('numeroSiret', models.CharField(max_length=20)),
            ],
            bases=('ramaqs_management_plateforme.utilisateur',),
        ),
        migrations.CreateModel(
            name='consultant',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ramaqs_management_plateforme.utilisateur')),
                ('competences', models.CharField(max_length=200)),
                ('disponibilite', models.BooleanField(default=True)),
                ('chargeTravail', models.IntegerField(default=0)),
                ('chefProjet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.chefprojet')),
            ],
            bases=('ramaqs_management_plateforme.utilisateur',),
        ),
        migrations.CreateModel(
            name='direction',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ramaqs_management_plateforme.utilisateur')),
                ('niveauAcces', models.CharField(max_length=50)),
            ],
            bases=('ramaqs_management_plateforme.utilisateur',),
        ),
        migrations.CreateModel(
            name='partenaire',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ramaqs_management_plateforme.utilisateur')),
                ('typePartenaire', models.CharField(max_length=50)),
                ('contrat', models.CharField(max_length=200)),
                ('dateDebutPartenariat', models.DateField()),
            ],
            bases=('ramaqs_management_plateforme.utilisateur',),
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField()),
                ('dateEnvoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(verbose_name=False)),
                ('typeMessage', models.CharField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=50)),
                ('message', models.CharField()),
                ('lue', models.BooleanField()),
                ('dateEnvoi', models.DateTimeField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('valeurCible', models.FloatField()),
                ('valeurActuelle', models.FloatField()),
                ('unite', models.CharField(max_length=255)),
                ('seuilAlerte', models.FloatField()),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.projet')),
            ],
        ),
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('chemin', models.FileField(upload_to='documents/')),
                ('version', models.CharField(max_length=20)),
                ('taille', models.IntegerField()),
                ('typeFichier', models.CharField(max_length=50)),
                ('dateUpload', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.projet')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.projet'),
        ),
        migrations.CreateModel(
            name='budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montantTotal', models.FloatField()),
                ('montantDepense', models.FloatField()),
                ('montantRestant', models.FloatField()),
                ('devise', models.CharField()),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='ramaqs_management_plateforme.projet')),
            ],
        ),
        migrations.CreateModel(
            name='ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('coutUnitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('projet', models.ManyToManyField(to='ramaqs_management_plateforme.projet')),
            ],
        ),
        migrations.CreateModel(
            name='tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priorite', models.CharField(max_length=50)),
                ('dateDebut', models.DateField()),
                ('dateFinPrevue', models.DateField()),
                ('dateFinReelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(max_length=50)),
                ('avancement', models.DecimalField(decimal_places=2, max_digits=5)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.projet')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.consultant')),
            ],
        ),
        migrations.CreateModel(
            name='sousTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('statut', models.CharField(max_length=50)),
                ('avancement', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dateEcheance', models.DateField()),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.tache')),
            ],
        ),
        migrations.CreateModel(
            name='commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('datePublication', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.utilisateur')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.tache')),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='chefProjet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.chefprojet'),
        ),
        migrations.AddField(
            model_name='projet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ramaqs_management_plateforme.client'),
        ),
        migrations.AddField(
            model_name='projet',
            name='partenaires',
            field=models.ManyToManyField(to='ramaqs_management_plateforme.partenaire'),
        ),
    ]
